# Generated by Django 4.1.5 on 2023-01-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=10, verbose_name='Coin Id')),
                ('coin_name', models.CharField(max_length=225, verbose_name='Coin Name')),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Current Price')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'DataStore',
                'verbose_name_plural': 'DataStores',
                'ordering': ['-cdate'],
            },
        ),
    ]
